project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic website of Dr. Sophie Vanbelle"
author-meta: "Dr. Sophie Vanbelle"

website:
  title: "Sophie Vanbelle"
  image: "files/profiles/vanbelle_square.JPG"
  description: "Academic website of Dr. Sophie Vanbelle"
 
  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu:
          - text: List of Publication
            href: publications.qmd
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Grants
            href: projects.qmd                                
      - text: Teaching
        href: teaching.qmd
      - text: Outreach
        menu:        
        - text: Presentations
          href: posts.qmd#category=presentation                   
      - text: PhD students
        href: people.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/svanbelle/academic_website
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Sophie Vanbelle](http://www.github.com/svanbelle) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/svanbelle
        target: _blank
 
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/svanbelle/academic_website
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://svanbelle.github.io/academic_website"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

